# Generated by Django 2.0 on 2017-12-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gig',
            old_name='preview_date',
            new_name='preview_date_hidden',
        ),
        migrations.AddField(
            model_name='gig',
            name='preview_date_admin',
            field=models.CharField(max_length=200, null=True, verbose_name='date'),
        ),
    ]
