# Generated by Django 2.0 on 2017-12-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0003_auto_20171225_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail for the youtube video', upload_to=''),
        ),
        migrations.AlterField(
            model_name='gig',
            name='preview_date_admin',
            field=models.CharField(blank=True, help_text='This will override the date above when shown on the site. Otherwise leave blank', max_length=200, null=True, verbose_name='date'),
        ),
    ]
