# Generated by Django 2.0 on 2017-12-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0004_auto_20171229_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='pub_date',
            field=models.DateTimeField(help_text="Use this to re-order the videos. This doesn't actually reflect the date of publication", null=True),
        ),
    ]
