# Generated by Django 2.0 on 2017-12-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0005_video_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, help_text="Use this to re-order the videos. This doesn't actually reflect the date of publication", null=True),
        ),
    ]
