# Generated by Django 2.0 on 2017-12-29 19:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0006_auto_20171229_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 29, 19, 11, 10, 416895, tzinfo=utc), help_text="Use this to re-order the videos. This doesn't actually reflect the date of publication", null=True),
        ),
    ]
