# Generated by Django 2.0 on 2017-12-29 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0008_auto_20171229_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='gig_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Use this to re-order the videos. This doesn't actually reflect the date of publication of the youtube video", null=True),
        ),
    ]
