# Generated by Django 2.0 on 2017-12-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0009_auto_20171229_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='gig_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
