# Generated by Django 2.0 on 2018-01-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0011_gig_jamboree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='jamboree',
            field=models.BooleanField(default=False, help_text='Tick this box and the gig with automatically be set to Jamboree recurring every 3rd Sunday of the month'),
        ),
    ]
