# Generated by Django 2.0 on 2018-01-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0012_auto_20180124_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='preview_date_hidden',
        ),
    ]
